name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      # - name: Install Playwright browsers
      #   run: npx playwright install --with-deps
      # - name: e2e tests
      #   run: npm run test:e2e
      # - if: ${{ github.event_name == 'push' }}
      #   uses: superfly/flyctl-actions/setup-flyctl@master
      # - if: ${{ github.event_name == 'push' }}
      #   run: flyctl deploy --remote-only
      #   env:
      #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Success Discord hook
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # severity: info
          # details: Deployment successful!
      # - name: Failure Discord hook
      #   if: ${{ failure() }}
      #   uses: rjstone/discord-webhook-notify@v1.0.4
      #   with:
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #     severity: error
      #     details: Deployment failed!
      # - name: Cancelled Discord hook
      #   if: ${{ cancelled() }}
      #   uses: rjstone/discord-webhook-notify@v1.0.4
      #   with:
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #     severity: warn
      #     details: Deployment cancelled!

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ','), '#skip') }}
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
